### PR TITLE
certs: add Files struct

### PR DESCRIPTION
**Pull request by kopiczko**
This encapsulates functionality which is repeated in all operators
allowing to loop over certificate files and add them as cloud config
assets, Azure KeyVault secrets or AWS encrypted blobs.

### CODE REVIEW

**Comment by MarcelMue** [comment]
This seems to also align all cert paths atleast across multiple installations, right?
Does this mean that all new clusters have their certs at `etc/kubernetes/ssl/...`?

**Comment by kopiczko** [comment]
Yes to both questions. Alignment was the goal here. I also think we may only need the Files struct and nothing more. I'll have to check the prometheus-config-controller.

**Comment by MarcelMue** [comment]
Ack, this is quite important for a few projects as we currently have values in `installations` multiple times to find different cert paths

**Comment by kopiczko** [comment]
Aren't values in installations for host clusters?

**Comment by xh3b4sd** [comment]
Yes, this here is about guest clusters.

**Comment by MarcelMue** [comment]
Okay, I was confused there - my bad.

(Explains my confusion about how this works haha)

**Pull request merged**
