### PR TITLE
Update legacy

### PR DESCRIPTION
**Pull request by xh3b4sd**
Yak shaving mode. I am working on the status magic so I get draining in Azure sorted eventually. Now the `statusresource` has to work with a hack meanwhile. So it deals with guest cluster API access and to get the vendor magic in the operators done the legacy branch has to be updated here because the `aws-operator` still uses this legacy crap.

### CODE REVIEW

**Review by tuommaki — APPROVED** [review]
LGTMIIWFY

**Review by kopiczko — APPROVED** [review]
Whatever you need in legacy, just merge...

**Review by MarcelMue — APPROVED** [review]
Unfortunate that we still need this, changes look fine though.

**Comment by xh3b4sd** [comment]
AFAIK the legacy crap is needed in AWS and we have still some older clusters there which should go away in a couple of days/weeks. Then we can cleanup some releases and code and refactor the certs usage. Then this crap is gone.

**Pull request merged**
